=== benjamingauthier/pictures-organizer-application/data/catalogue.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliotheque (catalogue+)>
<!ELEMENT catalogue (photo+)>
<!ELEMENT photo (titre,commentaire,htag+,date_modif)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT id (#PCDATA)>

<!ATTLIST photo taille CDATA #REQUIRED>
<!ATTLIST photo src CDATA #REQUIRED>
<!ATTLIST photo id CDATA #REQUIRED>
<!ATTLIST photo extention CDATA #REQUIRED>

=== benjamingauthier/pictures-organizer-application/CatalogueMVC/WebContent/WEB-INF/data/catalogue.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE catalogue SYSTEM "catalogue.dtd">
<?xml-stylesheet type="text/xsl" href= "catalogue.xsl" ?>
<bibliotheque>
	<catalogue id ="1" titre="vacance_usa2">
	  <photo src="images/autowp.ru_lamborghini_350gtv_10.jpg" id="1" taille="743679" extention=".jpg">
		<titre>Voiture_cool</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_350gtv_11.jpg" id="2" taille="536952" extention=".jpg">
		<titre>voiture_mega_cool</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_350gtv_6.jpg" id="3" taille="677289" extention=".jpg">
		<titre>voiture_de_thug</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_350gtv_8.jpg" id="4" taille="640842" extention=".jpg">
		<titre>autowp.ru_lamborghini_350gtv_8.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_countach_lp400_10.jpg" id="5" taille="396918" extention=".jpg">
		<titre>autowp.ru_lamborghini_countach_lp400_10.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_diablo_47.jpg" id="6" taille="1263329" extention=".jpg">
		<titre>autowp.ru_lamborghini_diablo_47.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_diablo_vt_6.0_23.jpg" id="7" taille="988317" extention=".jpg">
		<titre>autowp.ru_lamborghini_diablo_vt_6.0_23.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_espada_3.jpg" id="8" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_espada_3.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_gallardo_93.jpg" id="9" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_gallardo_93.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_gallardo_polizia_1.jpg" id="10" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_gallardo_polizia_1.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_gallardo_s.e._2.jpg" id="11" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_gallardo_s.e._2.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_gallardo_s.e._3.jpg" id="12" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_gallardo_s.e._3.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_gallardo_superleggera_51.jpg" id="13" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_gallardo_superleggera_51.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_jarama_400_10.jpg" id="14" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_jarama_400_10.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_jarama_400_11.jpg" id="15" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_jarama_400_11.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_lm002_9.jpg" id="16" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_lm002_9.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_murcielago_roadster_24.jpg" id="17" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_murcielago_roadster_24.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_reventon_58.jpg" id="18" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_reventon_58.jpg</titre>
	  </photo>
	</catalogue>
	<catalogue id ="2" titre="vacance_usa">
	  <photo src="images/autowp.ru_lamborghini_reventon_59.jpg" id="19" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_reventon_59.jpg</titre>
	  </photo>
	  <photo src="images/autowp.ru_lamborghini_silhouette_3.jpg" id="20" taille="665352" extention=".jpg">
		<titre>autowp.ru_lamborghini_silhouette_3.jpg</titre>
	  </photo>
	</catalogue>
</bibliotheque>
