=== benjamingauthier/pictures-organizer-application/CatalogueMVC/Data/catalogue.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalogue (photo+,sujet+)>
<!ELEMENT photo (titre,commentaire,htag+,date_modif)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date_modif (#PCDATA)>
<!ELEMENT commentaire (#PCDATA)>
<!ELEMENT htag (#PCDATA)>
<!ELEMENT sujet EMPTY>

<!ATTLIST photo taille CDATA #REQUIRED>
<!ATTLIST photo src CDATA #REQUIRED>
<!ATTLIST photo resolution CDATA #REQUIRED>
<!ATTLIST photo extention CDATA #REQUIRED>
<!ATTLIST photo signale CDATA #REQUIRED>
<!ATTLIST photo jaime (oui|non) "non">

<!ATTLIST sujet importance  (interessant|nonInteressant|default) "default">
<!ATTLIST sujet nom CDATA #REQUIRED>

=== benjamingauthier/pictures-organizer-application/CatalogueMVC/Data/catalogue.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE catalogue SYSTEM "catalogue.dtd">
<?xml-stylesheet type="text/xsl" href= "catalogue.xsl" ?>
<catalogue>
  <photo src="images/autowp.ru_lamborghini_350gtv_10.jpg" taille="743679" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_350gtv_10.jpg</titre>
    <commentaire>autowp.ru_lamborghini_350gtv_10.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_350gtv_10.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_350gtv_11.jpg" taille="536952" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_350gtv_11.jpg</titre>
    <commentaire>autowp.ru_lamborghini_350gtv_11.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_350gtv_11.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_350gtv_6.jpg" taille="677289" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_350gtv_6.jpg</titre>
    <commentaire>autowp.ru_lamborghini_350gtv_6.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_350gtv_6.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_350gtv_8.jpg" taille="640842" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_350gtv_8.jpg</titre>
    <commentaire>autowp.ru_lamborghini_350gtv_8.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_350gtv_8.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_countach_lp400_10.jpg" taille="396918" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_countach_lp400_10.jpg</titre>
    <commentaire>autowp.ru_lamborghini_countach_lp400_10.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_countach_lp400_10.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_diablo_47.jpg" taille="1263329" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_diablo_47.jpg</titre>
    <commentaire>autowp.ru_lamborghini_diablo_47.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_diablo_47.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:34</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_diablo_vt_6.0_23.jpg" taille="988317" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_diablo_vt_6.0_23.jpg</titre>
    <commentaire>autowp.ru_lamborghini_diablo_vt_6.0_23.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_diablo_vt_6.0_23.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_espada_3.jpg" taille="665352" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_espada_3.jpg</titre>
    <commentaire>autowp.ru_lamborghini_espada_3.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_espada_3.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_gallardo_93.jpg" taille="1063983" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_gallardo_93.jpg</titre>
    <commentaire>autowp.ru_lamborghini_gallardo_93.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_gallardo_93.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_gallardo_polizia_1.jpg" taille="727223" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_gallardo_polizia_1.jpg</titre>
    <commentaire>autowp.ru_lamborghini_gallardo_polizia_1.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_gallardo_polizia_1.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_gallardo_s.e._2.jpg" taille="541189" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_gallardo_s.e._2.jpg</titre>
    <commentaire>autowp.ru_lamborghini_gallardo_s.e._2.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_gallardo_s.e._2.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_gallardo_s.e._3.jpg" taille="516979" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_gallardo_s.e._3.jpg</titre>
    <commentaire>autowp.ru_lamborghini_gallardo_s.e._3.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_gallardo_s.e._3.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_gallardo_superleggera_51.jpg" taille="720430" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_gallardo_superleggera_51.jpg</titre>
    <commentaire>autowp.ru_lamborghini_gallardo_superleggera_51.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_gallardo_superleggera_51.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_jarama_400_10.jpg" taille="1520399" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_jarama_400_10.jpg</titre>
    <commentaire>autowp.ru_lamborghini_jarama_400_10.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_jarama_400_10.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_jarama_400_11.jpg" taille="1272394" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_jarama_400_11.jpg</titre>
    <commentaire>autowp.ru_lamborghini_jarama_400_11.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_jarama_400_11.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_lm002_9.jpg" taille="1015916" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_lm002_9.jpg</titre>
    <commentaire>autowp.ru_lamborghini_lm002_9.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_lm002_9.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
  <photo src="images/autowp.ru_lamborghini_murcielago_roadster_24.jpg" taille="135313" jaime="non" extention=".jpg" signale="0" resolution="1024*768">
    <titre>autowp.ru_lamborghini_murcielago_roadster_24.jpg</titre>
    <commentaire>autowp.ru_lamborghini_murcielago_roadster_24.jpg:La Lamborghini Gallardo est une voiture de sport du constructeur automobile italien Lamborghini. Sa conception est dirigée par Audi, propriétaire de la marque depuis 1998. </commentaire>
    <htag>autowp.ru_lamborghini_murcielago_roadster_24.jpgSuperleggera. </htag>
    <date_modif>04/02/2016 02:27:35</date_modif>
  </photo>
